version: "3.7"
services:
    app:
      image: node:latest
      working_dir: /usr/src/app
      tty: true
      ports: 
      - '3000:3000'
      volumes:
        - ./:/usr/src/app
      command: >
        bash -c "npm install &&
        npm install nodemon -g &&
        nodemon server.js"